# http://www.debian-administration.org/article/698/Automating_the_creation_of_docker_images
# Simple dockerfile for an ssh + server.
#
# Build it like so:
#
#   root@host~# docker build -t=etheride/runit - < Dockerfile.runit
#
# Launch the generated image like so,
# forwarding port 2222 on our machine to 22 in the container:
#
#   root@host~# docker run -d -p 2222:22 etheride/runit
#

#  From this base-image / starting-point
#FROM debootstrap/wheezy
FROM debian

#  Authorship
MAINTAINER ryan.sundberg@gmail.com

# Update apt
RUN apt-get update -q -q
RUN apt-get upgrade --yes --force-yes

# Install utitiles
RUN apt-get install less sudo screen --yes --force-yes

# Install runit
RUN apt-get install runit --yes --force-yes

# Install ssh
RUN apt-get install openssh-server openssh-client --yes --force-yes

RUN useradd -m sundbry
RUN mkdir -p /home/sundbry/.ssh
RUN echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCWvTZzEkfrm8vPSsx+ccSe6CHxAELN0qMJ/wN7d7t2bj+za3noTjmomtbz/C0PFLeM8uz1/JO4iT9uXSURARIRREDLQwB/XYkttfr8/usqC/E116szU9+EdOGaUzzKHiZxL+fzWrIpzFnTKVjRK+Vx0MJf6enTASs86Tf+YLjxTO6FO/UZTq4Oo+mnN8ITSmmIA38Ojxt2ZWwP26m9bAwvr6oVw3/yF4zjdziC7ksa/+BUPkF8wxAzjgzEhT5G37lgBGSxIBmt3dpGtS/x4XMH9Vbwzhcy8zpPdQCj3edu0N0y87PoaL3HchaJa/xyUNVlCbpB0BxkymmjQEN22sH5 sundbry@Ryans-MacBook-Pro.local" > /home/sundbry/.ssh/authorized_keys

# Expose the ssh port
EXPOSE 222

# Create sshd runit script
RUN mkdir /etc/service/sshd
RUN /bin/echo -e '#!/bin/sh' > /etc/service/sshd/run
RUN /bin/echo -e 'exec /usr/sbin/sshd -D -p 222' >> /etc/service/sshd/run

# Make sure our run-script is executable.
RUN chown root.root /etc/service/sshd/run
RUN chmod 755 /etc/service/sshd/run

# Finally launch runit.
ENTRYPOINT ["/usr/sbin/runsvdir-start"]
