repository: creeatist
loggly:
  token: 5741714c-b518-43a8-8968-bf971771a7ae
clusters:
  local:
    provider: vagrant
    nodes: 2
    coreos-channel: alpha
    master-mem-mb: 1024
    master-cpus: 1
    node-mem-mb: 4096
    node-cpus: 1
    kube-ui: true
  dalek:
    provider: ubuntu
    nodes: 1
    kube-ui: true
    nodes: "10.0.0.70"
    service-cluster-ip-range: "10.15.0.0/16"
    role: "ai"
    flannel-net: "172.0.16.0.0/16"
    dns-server-ip: "10.15.0.254"
    dns-domain: "dev.chowdr.us"
    dns-replicas: 1

#  environments:
#    development:
#      services:
#        chowder-api:
#        www:
