options:
  repository: creeatist
  cluster: dalek
  environment: development
loggly:
  token: 5741714c-b518-43a8-8968-bf971771a7ae
clusters:
  local:
    provider: vagrant
    nodes: 2
    coreos-channel: alpha
    master-mem-mb: 1024
    master-cpus: 1
    node-mem-mb: 4096
    node-cpus: 1
    kube-ui: true
  dalek:
    provider: ubuntu
    kube-server: 10.0.0.70:8080
    install-env:
      KUBE_VERSION: "1.0.7"
      nodes: "falcon@10.0.0.70"
      role: "ai"
      NUM_MINIONS: "1"
      SERVICE_CLUSTER_IP_RANGE: "10.0.15.0/16"
      FLANNEL_NET: "172.16.0.0/16"
      DOCKER_OPTS: "" 
      ENABLE_CLUSTER_DNS: "true"
      DNS_SERVER_IP: "10.0.15.254"
      DNS_DOMAIN: "dev.chowder.us"
      DNS_REPLICAS: "1"
      ENABLE_CLUSTER_UI: "true"
      KUBERNETES_PROVIDER: "ubuntu"

#  environments:
#    development:
#      services:
#        chowder-api:
#        www:
