local:
  clusters:
    main:
      provider: vagrant
      nodes: 2
      coreos-channel: alpha
      master-mem-mb: 1024
      master-cpus: 1
      node-mem-mb: 4096
      node-cpus: 1
      kube-ui: true
      base-ip: "10.100.0"
