options:
  repository: creeatist
  cluster: local
  environment: development

clusters:
  local:
    provider: native
    kube-server: 127.0.0.1:18080
  vagrant:
    provider: vagrant
    kube-server: todo-set-this:1234
    nodes: 2
    coreos-channel: alpha
    master-mem-mb: 1024
    master-cpus: 1
    node-mem-mb: 4096
    node-cpus: 1
    kube-ui: true
  dalek:
    provider: ubuntu
    kube-server: 10.0.0.70:8080
    install-env:
      KUBE_VERSION: "1.1.1"
      nodes: "falcon@10.0.0.70"
      role: "ai"
      NUM_MINIONS: "1"
      SERVICE_CLUSTER_IP_RANGE: "10.15.0.0/16"
      FLANNEL_NET: "172.16.0.0/16"
      DOCKER_OPTS: "" 
      ENABLE_CLUSTER_DNS: "true"
      DNS_SERVER_IP: "10.15.0.254"
      DNS_DOMAIN: "dalek.chowder.us"
      DNS_REPLICAS: "1"
      ENABLE_CLUSTER_UI: "true"
      KUBERNETES_PROVIDER: "ubuntu"
    #m4-params: # Cluster parameters
    #  CLUSTER_SUBNET: "10.15.0.0"
    #  CLUSTER_SUBNET_MASK: "255.255.0.0"
      

containers:
  base:
    m4-params: 
      LOGGLY_TOKEN: "5741714c-b518-43a8-8968-bf971771a7ae"
  riak-kv:
    m4-params: 
      RIAK_VERSION: "2.1.1-1"
  #chowdr-api:
    # TODO declarative container tag configuration
    #profiles:
    #  xyz:
    #    git-tag: xyz

environments:
  development:
    services:
      chowdr-api:
        secret-files:
          - chowdr-service.edn
          - log4j.properties
      kafka: 
        container-tag: 2015-12-04.004413
        secret-files:
          - log4j.properties
        profiles:
          node-0:
            m4-params:
              BROKER_ID: 0
              HOST_VOLUME_PATH: /var/local/kafka/0
          node-1:
            m4-params:
              BROKER_ID: 1
              HOST_VOLUME_PATH: /var/local/kafka/1
          node-2:
            m4-params:
              BROKER_ID: 2
              HOST_VOLUME_PATH: /var/local/kafka/2
        m4-params:
          ZOOKEEPER_CONNECT: zookeeper:2181
      # Not in use
      #kafka-zk:
      #  m4-params:
      #    HOST_VOLUME_PATH: /var/local/kafka-dev/0
      postgres:
        container-tag: "9.4"
        m4-params:
          POSTGRES_PASSWORD: m42SB#A7CJaNDdG$#bD8sGE5
          HOST_VOLUME_PATH: /var/local/postgres/0
      riak-kv:
        m4-params: 
          # To bootstrap a riak cluster, start 1 node, then scale it up to RIAK_CLUSTER_SIZE
          REPLICAS: 1
          RIAK_CLUSTER_SIZE: 3
      openvpn:
        m4-params:
          REPLICAS: 1
          VPN_VIRTUAL_NETWORK: "10.99.0.0" # New subnet for VPN clients
          VPN_VIRTUAL_MASK: "255.255.0.0" # Network mask
          VPN_VIRTUAL_NAT: "10.99.0.0/16" # Address space for VPN_VIRTUAL_NETWORK
          VPN_SUBNET_A_NETWORK: "172.16.75.0" # 1st subnet to route to
          VPN_SUBNET_A_MASK: "255.255.255.0"
          VPN_SUBNET_B_NETWORK: "10.15.0.0" # 2nd subnet to route to
      zookeeper:
        profiles:
          node-1:
            m4-params:
              ZK_ID: 1
          node-2:
            m4-params:
              ZK_ID: 2
          node-3:
            m4-params:
              ZK_ID: 3
        container-tag: 2015-12-03.191945
        m4-params:
          ZK_NODES: zookeeper-1,zookeeper-2,zookeeper-3


    
