repository: creeatist
loggly:
  token: 5741714c-b518-43a8-8968-bf971771a7ae
clusters:
  local:
    provider: vagrant
    nodes: 2
    coreos-channel: alpha
    master-mem-mb: 1024
    master-cpus: 1
    node-mem-mb: 4096
    node-cpus: 1
    kube-ui: true
  dalek:
    provider: native

#  environments:
#    development:
#      services:
#        chowder-api:
#        www:
