options:
  repository: creeatist
  cluster: local
  environment: development

clusters:
  local:
    provider: vagrant
    nodes: 2
    coreos-channel: alpha
    master-mem-mb: 1024
    master-cpus: 1
    node-mem-mb: 4096
    node-cpus: 1
    kube-ui: true
  dalek:
    provider: ubuntu
    kube-server: 10.0.0.70:8080
    install-env:
      KUBE_VERSION: "1.1.1"
      nodes: "falcon@10.0.0.70"
      role: "ai"
      NUM_MINIONS: "1"
      SERVICE_CLUSTER_IP_RANGE: "10.15.0.0/16"
      FLANNEL_NET: "172.16.0.0/16"
      DOCKER_OPTS: "" 
      ENABLE_CLUSTER_DNS: "true"
      DNS_SERVER_IP: "10.15.0.254"
      DNS_DOMAIN: "dalek.chowder.us"
      DNS_REPLICAS: "1"
      ENABLE_CLUSTER_UI: "true"
      KUBERNETES_PROVIDER: "ubuntu"
    #m4-params: # Cluster parameters
    #  CLUSTER_SUBNET: "10.15.0.0"
    #  CLUSTER_SUBNET_MASK: "255.255.0.0"
      

containers:
  base:
    m4-params: 
      LOGGLY_TOKEN: "5741714c-b518-43a8-8968-bf971771a7ae"
  riak-kv:
    m4-params: 
      RIAK_VERSION: "2.1.1-1"

environments:
  development:
    services:
      chowdr-api:
        secret-files:
          - chowdr-service.edn
      riak-kv:
        m4-params: 
          REPLICAS: 2
          RIAK_CLUSTER_SIZE: 3
      openvpn:
        m4-params:
          REPLICAS: 1
          VPN_VIRTUAL_NETWORK: "10.99.0.0" # New subnet for VPN clients
          VPN_VIRTUAL_MASK: "255.255.0.0" # Network mask
          VPN_VIRTUAL_NAT: "10.99.0.0/16" # Address space for VPN_VIRTUAL_NETWORK
          VPN_SUBNET_A_NETWORK: "172.16.75.0" # 1st subnet to route to
          VPN_SUBNET_A_MASK: "255.255.255.0"
          VPN_SUBNET_B_NETWORK: "10.15.0.0" # 2nd subnet to route to
    
