options:
  repository: creeatist # Docker repository
  cluster: dalek
  environment: development

clusters:
  local:
    provider: native
    kube-server: 127.0.0.1:18080
  vagrant:
    provider: vagrant
    kube-server: todo-set-this:1234
    params:
      NODES: 1
      CHANNEL: alpha
      MASTER_MEM: 1024
      MASTER_CPUS: 1
      NODE_MEM: 10240
      NODE_CPUS: 2
      USE_DOCKERCFG: true
      USE_KUBE_UI: true
  dalek:
    provider: ubuntu
    kube-server: 10.0.0.70:8080
    params:
      KUBE_VERSION: "1.1.1"
      nodes: "falcon@10.0.0.70"
      role: "ai"
      NUM_MINIONS: "1"
      SERVICE_CLUSTER_IP_RANGE: "10.15.0.0/16"
      FLANNEL_NET: "172.16.0.0/16"
      DOCKER_OPTS: "" 
      ENABLE_CLUSTER_DNS: "true"
      DNS_SERVER_IP: "10.15.0.254"
      DNS_DOMAIN: "dalek.chowder.us"
      DNS_REPLICAS: "1"
      ENABLE_CLUSTER_UI: "true"
      KUBERNETES_PROVIDER: "ubuntu"

containers:
  creeatist/base:
    m4-params: 
      LOGGLY_TOKEN: "5741714c-b518-43a8-8968-bf971771a7ae"
  chowdr-api:
    git-tag: 2016-01-04-c
  chowdr-client:
    git-tag: 2016-01-04-c
  riak-kv:
    m4-params: 
      RIAK_VERSION: "2.1.1-1"

environments:
  development:
    services:
      docker:
        secret-files:
          - config.json
      chowdr-shared:
        secret-files:
          - chowdr-shared.edn
          - log4j.properties
      chowdr-api:
        container-tag: 2015-12-10.014038
        secret-files:
          - chowdr-service.edn
      chowdr-client:
        container-tag: 2015-12-29.113943
        secret-files:
          - chowdr-service.edn
      hungry-py:
        container-tag: 2015-12-21.134511
        secret-files:
          - dbconfig.json
      jupyter:
        container-tag: 2016-01-03.233614
      kafka: 
        container-tag: 2015-12-04.010312
        secret-files:
          - log4j.properties
        profiles:
          node-0:
            m4-params:
              BROKER_ID: 0
              HOST_VOLUME_PATH: /var/local/kafka/0
          node-1:
            m4-params:
              BROKER_ID: 1
              HOST_VOLUME_PATH: /var/local/kafka/1
          node-2:
            m4-params:
              BROKER_ID: 2
              HOST_VOLUME_PATH: /var/local/kafka/2
        m4-params:
          ZOOKEEPER_CONNECT: zookeeper:2181
      # Not in use
      #kafka-standalone:
      #  m4-params:
      #    HOST_VOLUME_PATH: /var/local/kafka-dev/0
      postgres:
        container-tag: "9.4"
        m4-params:
          POSTGRES_PASSWORD: m42SB#A7CJaNDdG$#bD8sGE5
          HOST_VOLUME_PATH: /var/local/postgres/0
      riak-kv:
        m4-params: 
          # To bootstrap a riak cluster, start 1 node, then scale it up to RIAK_CLUSTER_SIZE
          REPLICAS: 1
          RIAK_CLUSTER_SIZE: 3
      openvpn:
        container-tag: 2015-12-08.184625
        m4-params:
          REPLICAS: 1
          VPN_VIRTUAL_NETWORK: "10.99.0.0" # New subnet for VPN clients
          VPN_VIRTUAL_MASK: "255.255.0.0" # Network mask
          VPN_VIRTUAL_NAT: "10.99.0.0/16" # Address space for VPN_VIRTUAL_NETWORK
          VPN_SUBNET_A_NETWORK: "172.16.75.0" # 1st subnet to route to
          VPN_SUBNET_A_MASK: "255.255.255.0"
          VPN_SUBNET_B_NETWORK: "10.15.0.0" # 2nd subnet to route to
          VPN_SUBNET_B_MASK: "255.255.0.0"
      spark-master:
        container-tag: 2016-01-04.011645
      spark-slave:
        container-tag: 2016-01-04.012412
        m4-params:
          REPLICAS: 2
          SPARK_WORKER_CORES: 1
          SPARK_WORKER_MEMORY: 2g
      zookeeper:
        profiles:
          node-1:
            m4-params:
              ZK_ID: 1
              HOST_VOLUME_PATH: /var/local/zookeeper/1
          node-2:
            m4-params:
              ZK_ID: 2
              HOST_VOLUME_PATH: /var/local/zookeeper/2
          node-3:
            m4-params:
              ZK_ID: 3
              HOST_VOLUME_PATH: /var/local/zookeeper/3
        container-tag: zk-with-log4j-2015-12-04-c
        secret-files:
          - log4j.properties
        m4-params:
          ZK_NODES: zookeeper-1,zookeeper-2,zookeeper-3
