#!/bin/sh

m4 -DBROKER_ID=$BROKER_ID \
  -DADVERTISED_HOST_NAME=$(hostname -i) \
  -DSERVER_PROPERTIES_PATH $SERVER_PROPERTIES_M4_PATH \
  -DKAFKA_LOG_DIRS=$KAFKA_LOG_DIRS \
  -DZOOKEEPER_CONNECT=$ZOOKEEPER_CONNECT
  > /etc/service/kafka/server.properties

export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:${LOG4J_PROPERTIES_PATH}"
/usr/local/kafka/bin/kafka-server-start.sh /etc/service/kafka/server.properties
