#!/bin/sh

LOCAL_HOST=`hostname -i`
# Servers must be named zookeeper-n
# Bind to the address on this machine, not the Kubernetes service address
echo "${LOCAL_HOST} zookeeper-${MYID}" >> /etc/hosts
echo ${MYID:-1} > ${ZOODATA}/myid

# server.1=...
if [ -n "$SERVERS" ]; then
  python -c "print '\n'.join(['server.%i=%s:2888:3888' % (i + 1, x) for i, x in enumerate('$SERVERS'.split(','))])" > ${ZOOCFGDIR}/servers.cfg
else
  echo > ${ZOOCFGDIR}/servers.cfg
fi

# Includes servers.cfg
m4 -I $ZOOCFGDIR \
  -DZOODATA=$ZOODATA \
  $ZOOCFG_M4 \
  > ${ZOOCFGDIR}/zoo.cfg

# Put log4j.properties in the right place
cp -f $LOG4J_PROPERTIES_PATH ${ZOOCFGDIR}/log4j.properties

/opt/zookeeper/bin/zkServer.sh start-foreground
