#!/bin/bash

cd /home/app
# cp -f secrets/chowder-service.edn tender/resources/chowder-service.edn
# chmod 0644 tender/resources/chowder-service.edn
cd tender
setuser app lein with-profile service run
