kind: Service
apiVersion: v1
metadata:
  name: app-service
  labels:
    name: app-service
spec:
  ports:
    - port: 3743
      targetPort: 3743
      protocol: TCP
  selector:
    role: app
  type: LoadBalancer
