kind: Service
apiVersion: v1
metadata:
  name: crossbar
  labels:
     name: crossbar
spec:
  ports:
    - port: 3745
      targetPort: 3745
      protocol: TCP
  selector:
    name: crossbar
  type: NodePort
