kind: Service
apiVersion: v1
metadata:
  name: openvpn
  labels:
     name: openvpn
spec:
  ports:
    - port: 1194
      targetPort: 1194
      protocol: TCP
  selector:
    name: openvpn
  type: LoadBalancer
